### ISSUE TITLE
Db Not Found 

### ISSUE THREAD

**Issue by Yo-ge-sh** [Lizaost/AlmatyTouristReactNative#1]
Db not fount 
can you add the DB file thanks

**Comment by Lizaost** [comment]
I've added both Russian and English language databases.
I do not know what you are going to do with this project further (maybe you will even try to pass it as your project in the exam at the university, which, to be honest, I will not be very happy), but if you are studying at IITU and your teacher is Dauletbek Ergali , then I do not recommend trying to pass off my work as yours. I handed over this project to him last semester and he has definitely not forgotten about it yet. Sorry if it sounded a little rude.

**Comment by Yo-ge-sh** [comment]
Hi ,
      Am not trying to take the project. The project seem nice so I wanted to use it as a reference to build my own app.

      I’ve already graduated so no issues of passing it as my own. Could you send me the data structure is possible if not the database.

Kind Regards,

**Comment by Lizaost** [comment]
Then excuse the suspicions.  The databases were added in the last commit.
I added them into a root folder, but I'm not sure if they are located at the right place. Unfortunately I have already deleted this project from my laptop. Try to move them to the Resources folder if the app won't work correctly with the current location of db files.

**Comment by Yo-ge-sh** [comment]
Thanks

Kind Regards,
Yogesh Boodhonee
